services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8001:8001"
    command: node dist/apps/auth/src/main.js

  event-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8002
      - MONGO_URI=${MONGO_URI}
    ports:
      - "8002:8002"
    command: node dist/apps/event/src/main.js

  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=8001
      - EVENT_SERVICE_HOST=event-service
      - EVENT_SERVICE_PORT=8002
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - event-service
    command: node dist/apps/gateway/src/main.js

networks:
  default:
    driver: bridge
